name: imaotai-action

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '2,11 1,9 * * *'

env:
  TZ: Asia/Shanghai

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    #    runs-on: windows-latest

    steps:
      - uses: actions/checkout
      - name: Set up Python 3.10
        uses: actions/setup-python
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      #          pip install pycryptodome requests beautifulsoup4

      - name: Cache pip
        uses: actions/cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: start run
        env:
          PUSHPLUS_KEY: ${{ secrets.PUSHPLUS_KEY }}
          PRIVATE_AES_KEY: ${{ secrets.PRIVATE_AES_KEY }}
          AMAP_KEY: ${{ secrets.AMAP_KEY }}
        run: |
          python main.py
